name: Run Certificate Job

on:
  schedule:
    - cron: '53 20 * * *'  # This will run the job every day at 2:56 PM UTC (8:26 PM IST). Adjust as needed.

jobs:
  run_certificate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install gspread
        pip install opencv-python-headless
        pip install pandas
        pip install google-auth-oauthlib
        pip install google-auth-httplib2

    - name: Run script
      run: python myproject.py
      env:
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
